### ISSUE TITLE
Database ID missing

### ISSUE THREAD

**Issue by AlimFreight** [Saad-ISAA/n8n-nodes-appwrite#1]
Hello , since appwrite move to different hierarchy to access documents the node should have option to setup database ID.
Now I am getting this error when I try to communicate to the Appwrite server.
`{"message":"404 - {\"message\":\"Database not found\",\"code\":404,\"type\":\"database_not_found\",\"version\":\"1.0.1\"}","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}`

**Comment by AlimFreight** [comment]
Another suggestion, I think it would be much easier to add a document if it was possible to add key-value pairs in the GUI instead of editing the original expression. Something like we do in the "SET-node"

![image](https://user-images.githubusercontent.com/54543689/196188586-ad127837-eb54-4ed4-b9bb-1a1e423ff466.png)

**Comment by Saad-ISAA** [comment]
I get it. I am looking into this

**Comment by Saad-ISAA** [comment]
@AlimFreight  the change is published https://www.npmjs.com/package/n8n-nodes-appwrite
Closing the issue
