### ISSUE TITLE
Databese ID missing

### ISSUE THREAD

**Issue by AlimFreight** [Saad-ISAA/n8n-nodes-appwrite#3]
I just updated node to version 0.1.3 bur still have the same issue.

![image](https://user-images.githubusercontent.com/54543689/196224223-a4824bdb-d6eb-4183-a45c-731a83b971db.png)

Where should I put database id?

**Comment by Saad-ISAA** [comment]
![image](https://user-images.githubusercontent.com/63791098/196250739-6f1c3ae3-0027-482c-a51e-9b2a1a0440dd.png)
@AlimFreight  I have just tested out on a fresh install from npm. it works perfectly..

can you please uninstall and reinstall maybe ? I am not sure what the issue would be

**Comment by AlimFreight** [comment]
I use Docker edition of N8N and only after I rebooted container I was able to see changes.
Now it's working properly, thank you!

**Comment by Saad-ISAA** [comment]
closing the issue
