### ISSUE TITLE
Id is not allowed for creating new documents.

### ISSUE THREAD

**Issue by AlimFreight** [Saad-ISAA/n8n-nodes-appwrite#5]
I would like to use a custom ID to create documents. For instance, I already have some unique number and I want to use it as an identifier.
In this version I can't do it, only auto-generated ID is supported. 

{
"message":
"400 - {"message":"$id is not allowed for creating new documents, try update instead","code":400,"type":"document_invalid_structure","version":"1.0.1"}",
"name":
"Error",
"stack":
"Error: Request failed with status code 400 at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}

**Comment by Saad-ISAA** [comment]
@AlimFreight Please share the API for doing so from appwrite documentation

**Comment by AlimFreight** [comment]
> @AlimFreight Please share the API for doing so from appwrite documentation

https://appwrite.io/docs/client/databases?sdk=web-default#databasesCreateDocument

`Document ID. Choose your own unique ID or pass the string "unique()" to auto generate it. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char. Max length is 36 chars.`

**Comment by Saad-ISAA** [comment]
I have published the updates as you've requested @AlimFreight 

https://www.npmjs.com/package/n8n-nodes-appwrite

**Comment by AlimFreight** [comment]
> I have published the updates as you've requested @AlimFreight
> 
> https://www.npmjs.com/package/n8n-nodes-appwrite

Thank you works as expected.

**Comment by Saad-ISAA** [comment]
> > I have published the updates as you've requested @AlimFreight
> > https://www.npmjs.com/package/n8n-nodes-appwrite
> 
> Thank you works as expected.

You are welcome brother... thanks for finding and pointing these updates.
